name: Release Notes Generation

on:
  push:
    branches:
      - main  

jobs:
  generate_release_notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  

      - name: Install dependencies
        run: npm install  

      - name: Grant execute permissions to the script
        run: chmod +x generate-release-notes.sh  

      - name: Generate release notes
        run: |
  
          echo "Generating release notes..."
          ./generate-release-notes.sh > release-notes.txt

      - name: Upload release notes
        uses: actions/upload-artifact@v2
        with:
          name: release-notes
          path: release-notes.txt  
