name: Deployment Pipeline

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build
      run: echo "Build"

  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Run Tests
      run: echo "Tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    - name: Add Heroku
      run: git remote add heroku https://git.heroku.com/i211226scdassignment2.git


    - name: Install Heroku CLI
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Login to Heroku
      run: heroku login --username=$saaramislam@gmail.com --password=$HRKU-95503637-0e1d-4c2c-8a0a-5138f453c5b6
      env:
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

