name: Documentation Deployment

on:
  push:
    branches:
      - main  # Adjust if you're using a different main branch name
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: pip install mkdocs mkdocs-material # Adjust for your project

    - name: Build Documentation
      run: mkdocs build --clean # Adjust for your project

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site # Adjust if your build output directory is different
        cname: your-custom-domain.com # Optional: Custom domain for GitHub Pages
