name: Documentation Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Generate documentation
        run: |
          npm install -g jsdoc
          jsdoc ./src/*.js -d ./docs
        working-directory: .

      - name: Configure Git
        run: |
          git config --global user.name "SaaramCheema"
          git config --global user.email "SaaramCheema@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GH_PAT }}
          publish_dir: ./docs
