name: Documentation Deployment

on:
  push:
    branches:
      - main  # Adjust the branch name if needed
  pull_request:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Adjust the Node.js version if needed
    
    - name: Install dependencies
      run: npm install  # Assuming you use npm for your documentation project
    
    - name: Generate documentation
      run: |
        npm install -g jsdoc
        jsdoc ./src/*.js -d ./docs
      working-directory: .  # Set the working directory to the root of your project
    
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: main
